"""
Register the merged Stage-1 graph directory in the cache manifest (after b3_graphs_fill).

    python -m lib.mllm.tools.register_graphs [--model qwen25vl_7b]

Key ``mllm/graphs/<model>`` is annotation-INDEPENDENT (graphs depend only on the
frames and on the Stage-1 model + prompts); the note records how many PKLs are
symlinks to the pre-existing /data/rohith/ag/graphs (never regenerated) and how
many were generated for test videos that had none, plus a hash of the two
Stage-1 prompt templates so a prompt change invalidates the cache key.
"""
from __future__ import annotations

import argparse
import hashlib
import os
import sys
from pathlib import Path

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
if REPO not in sys.path:
    sys.path.insert(0, REPO)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="qwen25vl_7b")
    args = ap.parse_args()
    from lib.mllm.core.config_loader import get_path, load_config
    from lib.mllm.core.prompts import CAPTION_GENERATION_PROMPT, GRAPH_PROMPT
    from lib.mllm.data.worldbbox import WorldBBoxTestSet
    from tools.cache_manifest import register
    cfg = load_config()
    d = Path(get_path(cfg, "graphs")) / args.model
    files = sorted(d.glob("*.pkl"))
    n_link = sum(1 for p in files if p.is_symlink())
    n_real = len(files) - n_link
    ts = WorldBBoxTestSet(cfg)
    have = {p.name.split(".")[0] for p in files}
    n_test = sum(1 for v in ts.video_ids if v in have)
    prompt_hash = hashlib.md5((CAPTION_GENERATION_PROMPT + GRAPH_PROMPT).encode("utf-8")).hexdigest()[:10]
    note = (f"Stage-1 graphs: {n_link} symlinks to /data/rohith/ag/graphs/{args.model} (pre-existing, never "
            f"regenerated) + {n_real} generated by lib.mllm.methods.graphs.runner --fast; test coverage "
            f"{n_test}/{len(ts.video_ids)}; prompt_hash={prompt_hash}")
    register(f"mllm/graphs/{args.model}", str(d), inputs=["frames_annotated", "frames", f"model:{args.model}",
                                                          f"prompt_hash:{prompt_hash}"],
             annotation_version=None, note=note)
    print(note)
    missing = [v for v in ts.video_ids if v not in have]
    if missing:
        print(f"WARNING: {len(missing)} test videos still have no graph, e.g. {missing[:5]}")


if __name__ == "__main__":
    main()
