class Constants:

    # ---------------------------------------------------------------
    # General + Common Keys
    # ---------------------------------------------------------------
    ADDITIONAL = "additional"
    ADAM = "adam"
    ADAMW = "adamw"
    ANNOTATIONS = "annotations"
    WORLD_ANNOTATIONS = "world_annotations"
    ASSIGNED_LABELS = "ASSIGNED_LABELS"
    ATTENTION_DISTRIBUTION = "attention_distribution"
    ATTENTION_LOGITS = "attention_logits"
    ATTENTION_GT = "attention_gt"
    ATTENTION_GT_MASK = "attention_gt_mask"
    ATTENTION_REL = "a_rel"
    ATTENTION_RELATION_LOSS = "attention_relation_loss"
    ATTENTION_RELATIONSHIP = "attention_relationship"
    BACKGROUND = "__background__"
    BASELINE_SO_ANT = "baseline_so_ant"
    BASELINE_SO_GEN_LOSS = "baseline_so_gen_loss"
    BBOX = "bbox"
    BOUNDING_BOX = "bbox"
    BOUNDING_BOX_SIZE = "bbox_size"
    BOXES = "boxes"
    BRIGHTNESS = "brightness"

    CLASS = "class"
    CONTACTING_DISTRIBUTION = "contacting_distribution"
    CONTACTING_GT = "contacting_gt"
    CONTACTING_GT_MASK = "contacting_gt_mask"
    CONTACTING_REL = "c_rel"
    CONTACTING_RELATION_LOSS = "contacting_relation_loss"
    CONTACTING_RELATIONSHIP = "contacting_relationship"
    CONTRAST = "contrast"
    CONTEXT_FRACTION = "context_fraction"
    CORRUPTION = "corruption"
    CORRUPTION_SEVERITY = "corruption_severity"
    CORRUPTION_SEVERITY_LEVEL = "corruption_severity_level"
    CUDA_DEVICE = 0

    DATE = "date"
    DATASET_CORRUPTION_MODE = "dataset_corruption_mode"
    DATASET_CORRUPTION_TYPE = "dataset_corruption_type"
    DEF0CUS_BLUR = "defocus_blur"
    DETECTOR_FOUND_IDX = "DETECTOR_FOUND_IDX"
    DISTRIBUTION = "distribution"
    DUST = "dust"
    DYSTTRAN = "dysttran"
    DYDSGDETR = "dydsgdetr"
    DYSGG = "dysgg"

    EASG = "easg"
    EVALUATION = "evaluation"
    ELASTIC_TRANSFORM = "elastic_transform"
    FEATURES = "features"
    FINAL_BASE_FEATURES = "FINAL_BASE_FEATURES"
    FINAL_BBOXES = "FINAL_BBOXES"
    FINAL_BBOXES_X = "FINAL_BBOXES_X"
    FINAL_DISTRIBUTIONS = "FINAL_DISTRIBUTIONS"
    FINAL_FEATURES = "FINAL_FEATURES"
    FINAL_FEATURES_X = "FINAL_FEATURES_X"
    FINAL_LABELS = "FINAL_LABELS"
    FINAL_LABELS_X = "FINAL_LABELS_X"
    FINAL_PRED_SCORES = "FINAL_PRED_SCORES"
    FINAL_SCORES = "FINAL_SCORES"
    FINAL_SCORES_X = "FINAL_SCORES_X"
    FIXED = "fixed"
    FOG = "fog"
    FOG = "fog"
    FMAPS = "fmaps"
    FRAME = "frame"
    FRAMES = "frames"
    FRAME_IDX = "frame_idx"
    FRAME_SIZE = "frame_size"

    GAUSSIAN_BLUR = "gaussian_blur"
    GAUSSIAN_NOISE = "gaussian_noise"
    GENERATION_IMPACT = "generation_impact"
    GLOVE_6B = "glove.6B"
    GLASS_BLUR = "glass_blur"
    GT_ANNOTATION = "gt_annotation"
    GT_RELATION_MASKS = "GT_RELATION_MASKS"
    GT_RELATIONS = "GT_RELATIONS"

    HARMONIC_RECALL_10 = "harmonic_recall_10"
    HARMONIC_RECALL_20 = "harmonic_recall_20"
    HARMONIC_RECALL_50 = "harmonic_recall_50"
    HARMONIC_RECALL_100 = "harmonic_recall_100"
    HUMAN_IDX = "human_idx"

    IMAGE_IDX = "im_idx"
    IM_IDX = "im_idx"
    IM_INFO = "im_info"
    IMPULSE_NOISE = "impulse_noise"
    INDICES = "indices"
    JPEG_COMPRESSION = "jpeg_compression"

    LABELNOISE = "labelnoise"
    LABELNOISE_PERCENTAGE = "label_noise_percentage"
    LABELS = "labels"
    LABEL_NOISE = "label_noise"
    MEAN_RECALL_10 = "mean_recall_10"
    MEAN_RECALL_20 = "mean_recall_20"
    MEAN_RECALL_50 = "mean_recall_50"
    MEAN_RECALL_100 = "mean_recall_100"
    METADATA = "metadata"
    MINI = "mini"
    MIXED = "mixed"
    MODE = "mode"
    MOTION_BLUR = "motion_blur"

    NEURALSDE = "NeuralSDE"
    NEURALODE = "NeuralODE"
    NMS_THRESHOLD = 0.4
    NO_CONSTRAINT_METRICS = "no_constraint_metrics"
    NO_CORRUPTION = "no_corruption"
    OBJECT = "object"
    OBJECT_BOUNDING_BOX_RELATIONSHIP_FILTERSMALL_PKL = "object_bbox_and_relationship_filtersmall.pkl"
    OBJECT_BOUNDING_BOX_RELATIONSHIP_PKL = "object_bbox_and_relationship.pkl"
    OBJECT_CLASSES_FILE = "object_classes.txt"
    OBJECT_LOSS = "object_loss"

    PAIR = "pair"
    PAIR_IDX = "pair_idx"
    PARTIAL = "partial"
    PARTIAL_PERCENTAGE = "partial_percentage"
    PERCENTAGE_EVALUATION = "percentage_evaluation"
    PERSON = "person"
    PERSON_BOUNDING_BOX = "person_bbox"
    PERSON_BOUNDING_BOX_PKL = "person_bbox.pkl"
    PEXELATE = "pixelate"
    PREDCLS = "predcls"
    PRED_LABELS = "pred_labels"
    PRED_SCORES = "pred_scores"
    PROGRESS_TEXT_FILE = "progress.txt"

    RAIN = "rain"
    RECALL_10 = "recall_10"
    RECALL_20 = "recall_20"
    RECALL_50 = "recall_50"
    RECALL_100 = "recall_100"
    RELATIONSHIP_CLASSES_FILE = "relationship_classes.txt"
    RESULT_DETAILS = "result_details"
    RESULT_ID = "result_id"
    RESULTS = "results_eccv"

    SDD = "sgdet"
    SDE = "sde"
    SCORE_THRESHOLD = 0.1
    SCORES = "scores"
    SCENARIO_NAME = "scenario_name"
    SET = "set"
    SGCLS = "sgcls"
    SGDET = "sgdet"
    SGG = "sgg"
    SGA = "sga"
    SHOT_NOISE = "shot_noise"
    SNOW = "snow"
    SPATIAL_DISTRIBUTION = "spatial_distribution"
    SPATIAL_GT = "spatial_gt"
    SPATIAL_GT_MASK = "spatial_gt_mask"
    SPATIAL_MASKS = "spatial_masks"
    SPATIAL_REL = "s_rel"
    SPATIAL_RELATION_LOSS = "spatial_relation_loss"
    SPATIAL_RELATIONSHIP = "spatial_relationship"
    SPECKLE_NOISE = "speckle_noise"
    SPATTER = "spatter"
    STATE_DICT = "state_dict"
    STL_LOSS = "stl_loss"
    STTRAN = "sttran"
    SUPPLY_RELATIONS = "SUPPLY_RELATIONS"
    SUPPLY_RELATION_MASKS = "SUPPLY_RELATION_MASKS"
    SUN_GLARE = "sun_glare"
    SUPERVISED = "supervised"

    TAG = "tag"
    TASK_NAME = "task_name"
    TEMPURA = "tempura"
    TEST = "test"
    TEST_FUTURE_FRAMES = "test_future_frames"
    TEST_NUM_FUTURE_FRAMES = "test_num_future_frames"
    TRACE = "trace"
    TRAIN = "train"
    TRAIN_FUTURE_FRAMES = "train_future_frames"
    TRAIN_NUM_FUTURE_FRAMES = "train_num_future_frames"

    UNION_BOX = "union_box"
    UNION_FEAT = "union_feat"
    UNION_FEATURES = "union_features"
    VISIBLE = "visible"
    VIDEO_CORRUPTION_MODE = "video_corruption_mode"

    WATERDROP = "waterdrop"
    WILDFIRE_SMOKE = "wildfire_smoke"
    WITH_CONSTRAINT_METRICS = "with_constraint_metrics"

    ZOOM_BLUR = "zoom_blur"