"""Sandbox for one-off MLLM runs on videos outside the WorldBBox split (figure intermediates).

Everything the runners write (graphs, runs, caches, LLM cache, logs, status files) is redirected
under SB, and the annotation dir / split file point at symlinks to the chosen PKLs, so nothing
touches the shared WorldBBox runs, caches or manifest.

usage: python make_sandbox.py <sandbox dir> <video>=<annotation pkl> [<video>=<pkl> ...]
"""
import os
import sys
from pathlib import Path

import yaml

REPO = Path(os.path.expanduser("~/CODE/Scene4Cast_mllm"))
SB = Path(sys.argv[1])
pairs = [a.split("=", 1) for a in sys.argv[2:]]

for sub in ("annotations", "graphs", "runs", "cache/bev", "cache/detections", "cache/lifted3d",
            "cache/llm_cache", "logs", "capture", "tools"):
    (SB / sub).mkdir(parents=True, exist_ok=True)

for vid, pkl in pairs:
    link = SB / "annotations" / f"{vid}.mp4.pkl"
    if link.is_symlink() or link.exists():
        link.unlink()
    link.symlink_to(pkl)
(SB / "split.txt").write_text("".join(f"{v}\n" for v, _ in pairs))

cfg = yaml.safe_load(open(REPO / "configs" / "mllm" / "server.yaml"))
p = cfg["paths"]
p["graphs"] = str(SB / "graphs") + "/"
p["cache_root"] = str(SB)
outs = p["outputs"]
for k in list(outs):
    outs[k] = str(SB / "runs" / k) + "/"
outs["graphs"] = str(SB / "graphs") + "/"
outs["logs"] = str(SB / "logs") + "/"
wb = p["worldbbox"]
wb["annotations_test"] = str(SB / "annotations") + "/"
wb["annotation_version_name"] = "figure_sandbox"
wb["split_file"] = str(SB / "split.txt")
wb["manifest"] = str(SB / "manifest.json")
wb["caches"] = {k: str(SB / "cache" / k) + "/" for k in ("bev", "detections", "lifted3d", "llm_cache")}
with open(SB / "config.yaml", "w") as f:
    f.write("# Figure-intermediate sandbox (generated by make_sandbox.py); everything written stays under\n"
            f"# {SB}\n")
    yaml.safe_dump(cfg, f, sort_keys=False)

print((SB / "split.txt").read_text().strip().replace("\n", ", "))
for vid, _ in pairs:
    link = SB / "annotations" / f"{vid}.mp4.pkl"
    print(f"{link} -> {os.readlink(link)}")
leaks = [f"{k}={v}" for k, v in yaml.safe_load(open(SB / "config.yaml"))["paths"]["outputs"].items()
         if not str(v).startswith(str(SB))]
print("outputs outside the sandbox:", leaks or "none")
