#!/usr/bin/env python3
"""
Generate the WorldWise+ / WorldWise++ configs.

WorldWise+ (formerly "WorldFormer C1") — byte-for-byte the C1 config of the same
stream/mode except the method, experiment and save-path names:

    configs/methods/<mode>/worldwise_plus_<stream>_<mode>.yaml   stream in {dinov3tok, pi3tok, fused}
        method_name: worldwise_plus | experiment_name: worldwise_plus_<stream>_<mode>
        save_path: /data3/rohith/ag/runs/worldwise_plus

WorldWise++ — from worldwise_plus_dinov3tok_<mode> (feature_model dinov3_tok, 3072-d
Tier-1 tokens for the slot appearance) plus the entity-decoder / detection keys:

    configs/methods/<mode>/worldwise_pp_dinov3_<mode>.yaml
    configs/methods/<mode>/worldwise_pp_dinov3_nodet_<mode>.yaml   (n_free_queries 0, lambda_det 0,
                                                                     lambda_slot_box 0 — no joint detection)

    python tools/gen_worldwise_variant_configs.py
"""
import os
import sys

import yaml

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STREAMS = ("dinov3tok", "pi3tok", "fused")
PLUS_SAVE = "/data3/rohith/ag/runs/worldwise_plus"
PP_SAVE = "/data3/rohith/ag/runs/worldwise_pp"
GRID_CACHE = "/data3/rohith/ag/cache/pp_grids"

HEADER_PLUS = """# ============================================================================
# worldwise_plus  |  mode={mode}  |  tokens={fm}  |  base = WorldWise v2e @ dinov3l
# WorldWise+ (formerly WorldFormer C1): identical to worldformer_c1_{stream}_{mode}.yaml
# except method_name / experiment_name / save_path. Generated by
# tools/gen_worldwise_variant_configs.py.
# Usage:
#   python train_wsgg_methods.py --config configs/methods/{mode}/{stem}.yaml
# ============================================================================
"""
HEADER_PP = """# ============================================================================
# worldwise_pp  |  mode={mode}  |  slot tokens=dinov3_tok  |  grids=DINOv3 L24n + Pi3 G14 (PCA-256)
# WorldWise++: entity decoder over fused token grids + joint free-query detection
# + EGTR-style relation readout ({variant}). Generated by
# tools/gen_worldwise_variant_configs.py from worldwise_plus_dinov3tok_{mode}.yaml.
# Usage:
#   python train_wsgg_methods.py --config configs/methods/{mode}/{stem}.yaml
# ============================================================================
"""

PP_KEYS = {
    "grid_cache_root": GRID_CACHE,
    "grid_cache_allow_missing": False,
    "d_grid": 256,
    "n_free_queries": 30,
    "n_decoder_layers": 4,
    "n_decoder_heads": 8,
    "d_decoder_ff": 1024,
    "max_frames": 1024,
    "lambda_det": 1.0,
    "lambda_slot_box": 1.0,
    "det_one_to_many_iou": 0.5,
    "det_no_object_weight": 0.1,
}
PP_NODET = {"n_free_queries": 0, "lambda_det": 0.0, "lambda_slot_box": 0.0}


def _write(path, header, cfg):
    with open(path, "w", newline="\n", encoding="utf-8") as f:
        f.write(header)
        yaml.safe_dump(cfg, f, sort_keys=False)
    print(path)


def main():
    for mode in ("predcls", "sgdet"):
        cdir = os.path.join(REPO, "configs", "methods", mode)
        plus_base = None
        for stream in STREAMS:
            src = os.path.join(cdir, f"worldformer_c1_{stream}_{mode}.yaml")
            with open(src, encoding="utf-8") as f:
                cfg = yaml.safe_load(f)
            stem = f"worldwise_plus_{stream}_{mode}"
            cfg.update({"method_name": "worldwise_plus", "experiment_name": stem, "save_path": PLUS_SAVE})
            _write(os.path.join(cdir, f"{stem}.yaml"),
                   HEADER_PLUS.format(mode=mode, fm=cfg["feature_model"], stream=stream, stem=stem), cfg)
            if stream == "dinov3tok":
                plus_base = dict(cfg)

        for variant, extra in (("full", {}), ("nodet", PP_NODET)):
            cfg = dict(plus_base)
            stem = f"worldwise_pp_dinov3_{mode}" if variant == "full" else f"worldwise_pp_dinov3_nodet_{mode}"
            cfg.update({"method_name": "worldwise_pp", "experiment_name": stem, "save_path": PP_SAVE})
            cfg.update(PP_KEYS)
            cfg.update(extra)
            _write(os.path.join(cdir, f"{stem}.yaml"),
                   HEADER_PP.format(mode=mode, stem=stem,
                                    variant="full model" if variant == "full" else
                                    "ablation: no free queries, no detection / slot-box losses"), cfg)


if __name__ == "__main__":
    sys.exit(main())
