#!/usr/bin/env python3
"""
Generate the WorldFormer C1 token-swap configs from the WorldWise main config
(v2e @ dinov3l) — only the appearance input changes:

    configs/methods/<mode>/worldformer_c1_<stream>_<mode>.yaml
        stream in {dinov3tok, pi3tok, fused}; mode in {predcls, sgdet}

    feature_model  : dinov3_tok | pi3_tok | fused   (derived PKLs, see derive_roi_features.py)
    d_detector_roi : 3072 | 3072 | 6144    d_union_roi: same
    token_streams  : [3072] | [3072] | [3072, 3072]      fusion: gated
    save_path      : /data3/rohith/ag/runs/worldformer   (/data is full)

    python tools/gen_worldformer_c1_configs.py
"""
import os
import sys

import yaml

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STREAMS = {
    "dinov3tok": ("dinov3_tok", [3072]),
    "pi3tok": ("pi3_tok", [3072]),
    "fused": ("fused", [3072, 3072]),
}
HEADER = """# ============================================================================
# worldformer_c1  |  mode={mode}  |  tokens={fm}  |  base = WorldWise v2e @ dinov3l
# Generated by tools/gen_worldformer_c1_configs.py — appearance input swapped for
# cached foundation tokens (datasets/preprocess/tokens/derive_roi_features.py).
# Usage:
#   python train_wsgg_methods.py --config configs/methods/{mode}/{stem}.yaml
# ============================================================================
"""


def main():
    for mode in ("predcls", "sgdet"):
        base_path = os.path.join(REPO, "configs", "methods", mode, f"worldwise_{mode}_dinov3l.yaml")
        with open(base_path) as f:
            base = yaml.safe_load(f)
        for key, (fm, streams) in STREAMS.items():
            cfg = dict(base)
            stem = f"worldformer_c1_{key}_{mode}"
            cfg.update({
                "method_name": "worldformer_c1",
                "feature_model": fm,
                "d_detector_roi": sum(streams),
                "d_union_roi": sum(streams),
                "token_streams": streams,
                "fusion": "gated",
                "experiment_name": stem,
                "save_path": "/data3/rohith/ag/runs/worldformer",
                "use_wandb": False,
                "train_annot_dir": "world4d_rel_annotations",
                "test_annot_dir": "world4d_rel_annotations_worldbbox",
            })
            out = os.path.join(REPO, "configs", "methods", mode, f"{stem}.yaml")
            with open(out, "w", newline="\n", encoding="utf-8") as f:
                f.write(HEADER.format(mode=mode, fm=fm, stem=stem))
                yaml.safe_dump(cfg, f, sort_keys=False)
            print(out)


if __name__ == "__main__":
    sys.exit(main())
